### ISSUE TITLE
Tests always passing

### ISSUE THREAD

**Issue by TxHawks** [JohnAlbin/sassy-test#2]
For some reason, my tests never fail.

I have the following scenario, just to check that a test could fail:
```js
'use strict';                    
                                 
describe('jigsass-px2em', () => {
  describe('jig-px2em function', () => {
    describe('Conversion of unitless numbers', () => {
      it('Should warn when both `$px` and `$context` are unitless', ()=> {                       
        sassyTest.renderFixture('px2em-unitless', sassyTestOptions, (err, result, expected) => { 
          should.not.exist(err);                                                                 
                                                                                                
          // result.warn[2].should.equal('jig-px2em: Assuming 24 is in pixels');                    
          // result.warn[3].should.equal('jig-px2em: Assuming `context` 24 is in pixels');          
          assert.srictEqual(results.css, 'dslkfj');                                              
          done();                                                                                
        });
      });                                                                                      
    });                                                                                        
  });                                                                                      
});                                                                                        
```

**Comment by TxHawks** [comment]
My bad - I had a typo in the `fixtures` dir.

**Comment by TxHawks** [comment]
Turns out it wasn't just the typo....

Result seems to be `null` for some reason.

The path to the fixture is correct, and the content of `input.scss` is:
```scss
@import 'index.scss';
               
test-unitless-conversion {
  unitless-px-no-context: jig-px2em(24);
  unitless-px-with-px-context: jig-px2em(24, 24px);
  unitless-px-with-unitless-context: jig-px2em(24, 24);
  pixel-px-with-unitless-context: jig-px2em(24px, 24);
}                                                      
```

The error I get from Mocha is:
```sh
Uncaught AssertionError: 
  '' === 'test-unitless-conversion {\n  
    unitless-px-no-context: 1.5em;\n
    unitless-px-with-px-context: 1em;\n  
    unitless-px-with-unitless-
      + expected - actual

      +test-unitless-conversion {
      +  unitless-px-no-context: 1.5em;
      +  unitless-px-with-px-context: 1em;
      +  unitless-px-with-unitless-context: 1em;
      +  pixel-px-with-unitless-context: 1em;
      +}
```

So `output.css` is imported correctly, but `input.scss` isn't. At first I thought it may be an `includePaths` issue, and not managing to find `index.scss`, but even then, something should have been in `result`, even if not compiled correctly.

Any ideas would really be appreciated.
